apiVersion: apps/v1
kind: Deployment
metadata:
  name: iplprediction-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iplprediction
  template:
    metadata:
      labels:
        app: iplprediction
    spec:
      containers:
      - name: iplprediction-container
        image: rameshkumarverma/iplprediction:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iplprediction-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: iplprediction
